# Generated by Django 4.0.1 on 2022-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=1)),
            ],
        ),
    ]
