# Generated by Django 4.0.1 on 2022-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_1', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_staffs',
                'ordering': ['fullname', 'department'],
            },
        ),
    ]
