# Generated by Django 4.0.1 on 2022-02-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='news',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
